FROM docker.io/library/node:22-alpine AS base

WORKDIR /app

# Install build dependencies
COPY ./package.json ./
COPY ./package-lock.json ./
RUN npm install -g npm@latest && \
    npm install -g @angular/cli && \
    npm install --legacy-peer-deps

# Copy app source
COPY ./src ./src
COPY ./angular.json ./
COPY ./tsconfig.app.json ./
COPY ./tsconfig.json ./
COPY ./tsconfig.spec.json ./


FROM base AS dev

ENV FRONTEND_PORT 8000
ENV BACKEND_PORT 8001
ENV BACKEND_HOST localhost

COPY ./proxy.dev.conf.js ./

EXPOSE 8000
CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--port", "8000", "--proxy-config", "proxy.dev.conf.js", "--poll=2000"]


FROM base AS build

ARG APP_URL_DEST

RUN if [[ "${APP_URL_DEST}" == "" ]] ; \
  then \
    echo "\n" | ng build --configuration=production --base-href=/ ; \
  else \
    echo "\n" | ng build --configuration=production --base-href=/${APP_URL_DEST}/ ; \
  fi


FROM docker.io/library/nginx:alpine as prod

# set env variable defaults
ENV FRONTEND_PORT 8000
ENV BACKEND_PORT 8001
ENV BACKEND_HOST localhost

# copy compiled angular app from build
COPY --from=build /app/dist/lipidlibrarianweb/browser /usr/share/nginx/html

# prepare nginx configuration
ENV NGINX_ENVSUBST_OUTPUT_DIR /tmp
RUN rm -rf /etc/nginx/conf.d
COPY ./nginx/lipidlibrarianweb.conf.template /etc/nginx/templates/
COPY ./nginx/nginx.conf /etc/nginx/
EXPOSE 8000
