FROM python:3.11 AS build-step

# set environment variables
ARG LIPIDLIBRARIAN_GIT_BRANCH

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL True

WORKDIR /app

# Install pipeline and container-entrypoint.sh dependencies
RUN apt-get update && apt-get install -y \
 python3-venv \
 netcat-openbsd \
 git

# Clone and Checkout LipidLibrarian
RUN git clone --single-branch --branch ${LIPIDLIBRARIAN_GIT_BRANCH} https://github.com/LipiTUM/lipidlibrarian.git /app/lipidlibrarian
WORKDIR /app/lipidlibrarian

# Install virtual environment to /app/venv
ENV PATH="/app/venv/bin:$PATH"
RUN ln -sf /app/lipidlibrarian/venv /app/venv

# Install LipidLibrarian
RUN make install

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir --upgrade pip && \
 pip install --no-cache-dir -r requirements.txt


FROM python:3.11

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL True
ENV PATH="/app/venv/bin:$PATH"

WORKDIR /app

COPY --from=build-step /app/lipidlibrarian/venv /app/venv

# Bundle app source
COPY ./lipidlibrarianweb ./lipidlibrarianweb
COPY ./lipidlibrarianweb_api ./lipidlibrarianweb_api
COPY ./manage.py ./
COPY ./container-entrypoint.sh ./

# Prepare the start command
RUN chmod +x container-entrypoint.sh
ENTRYPOINT ["/app/container-entrypoint.sh"]
