FROM docker.io/library/python:3.11 as base

# set environment variables
ARG LIPIDLIBRARIAN_GIT_BRANCH

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL True

WORKDIR /app

# Install pipeline and container-entrypoint.sh dependencies
RUN apt-get update && apt-get install -y \
 python3-venv \
 netcat-openbsd \
 git

# Clone and Checkout LipidLibrarian
RUN git clone --single-branch --branch ${LIPIDLIBRARIAN_GIT_BRANCH} https://github.com/LipiTUM/lipidlibrarian.git /app/lipidlibrarian

# Install LipidLibrarian
WORKDIR /app/lipidlibrarian
RUN make install
ENV PATH="/opt/venv/bin:$PATH"
RUN mv /app/lipidlibrarian/venv /opt/venv
RUN ln -sf /opt/venv /app/lipidlibrarian/venv
RUN ln -sf /opt/venv /app/venv
WORKDIR /app

# Install django rest framework
COPY requirements.txt ./
RUN pip install --no-cache-dir --upgrade pip && \
 pip install --no-cache-dir -r requirements.txt

# Bundle app source
COPY ./lipidlibrarianweb ./lipidlibrarianweb
COPY ./lipidlibrarianweb_api ./lipidlibrarianweb_api
COPY ./manage.py ./


FROM base AS dev

ENV BACKEND_PORT=8001
ENV DJANGO_SETTINGS_MODULE=lipidlibrarianweb.settings.dev

COPY ./container-entrypoint.dev.sh /container-entrypoint.sh
RUN chmod +x /container-entrypoint.sh

EXPOSE 8001
ENTRYPOINT ["/container-entrypoint.sh"]


FROM base AS prod

ENV BACKEND_PORT=8001
ENV DJANGO_SETTINGS_MODULE=lipidlibrarianweb.settings.prod

COPY ./container-entrypoint.prod.sh ./container-entrypoint.sh
RUN chmod +x container-entrypoint.sh

EXPOSE 8001
ENTRYPOINT ["/app/container-entrypoint.sh"]
CMD ["backend"]
